InfCommerce.WebUI/ViewModels/FooterVM.cs
using InfCommerce.DAL.Entities;
using System.Collections.Generic;

namespace InfCommerce.WebUI.ViewModels
{
    public class FooterVM
    {
        public IEnumerable<Brand> Brands { get; set; }
        public IEnumerable<News> Newses { get; set; }
    }
}

InfCommerce.WebUI/ViewModels/IndexVM.cs
using InfCommerce.DAL.Entities;
using System.Collections.Generic;

namespace InfCommerce.WebUI.ViewModels
{
    public class IndexVM
    {
        public IEnumerable<Slider> Slider { get; set; }
        public IEnumerable<Product> LatestProducts { get; set; }
        public IEnumerable<Product> BestSellerProducts { get; set; }
    }
}

InfCommerce.WebUI/ViewModels/ProductVM.cs
using InfCommerce.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace InfCommerce.WebUI.ViewModels
{
    public class ProductVM
    {
        public IEnumerable<Product> SimilarProducts { get; set; }
        public Product Product { get; set; }
    }
}

InfCommerce.WebUI/Areas/admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InfCommerce.WebUI.Areas.admin.Controllers
{
    [Area("admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("/admin/giris"),AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }
        [Route("/admin/giris"), AllowAnonymous,HttpPost]
        public IActionResult Login(string mailaddress,string password)
        {
            return View();
        }
    }
}

InfCommerce.WebUI/Areas/admin/Controllers/SliderController.cs
using InfCommerce.DAL.DbContexts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InfCommerce.WebUI.Areas.admin.Controllers
{
    [Area("admin")]
    public class SliderController : Controller
    {
        private readonly SqlContext sqlContext;

        public SliderController(SqlContext sqlContext)
        {
            this.sqlContext = sqlContext;
        }
        public IActionResult Index()
        {
            var model = sqlContext.Slider.ToList();

            return View(model);
        }
    }
}

InfCommerce.WebUI/Controllers/HomeController.cs
using InfCommerce.BL.Repositories;
using InfCommerce.DAL.Entities;
using InfCommerce.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace InfCommerce.WebUI.Controllers
{
    public class HomeController : Controller
    {
        SqlRepo<Slider> repoSlider;
        SqlRepo<Product> repoProduct;
        public HomeController(SqlRepo<Slider> _repoSlider, SqlRepo<Product> _repoProduct)
        {
            repoSlider = _repoSlider;
            repoProduct = _repoProduct;
        }
        public IActionResult Index()
        {
            IndexVM indexVM = new IndexVM
            {
                Slider = repoSlider.GetAll(),
                LatestProducts = repoProduct.GetAll().Include(i => i.ProductPictures).OrderByDescending(o => o.ID).Take(5),
                BestSellerProducts = repoProduct.GetAll().Include(i => i.ProductPictures).OrderBy(o => Guid.NewGuid()).Take(8)
            };
            return View(indexVM);
        }

        public IActionResult Test()
        {
            return View();
        }
    }
}

InfCommerce.WebUI/Controllers/ProductController.cs
using InfCommerce.BL.Repositories;
using InfCommerce.DAL.Entities;
using InfCommerce.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace InfCommerce.WebUI.Controllers
{
    public class ProductController : Controller
    {
        SqlRepo<Product> repoProduct;
        public ProductController(SqlRepo<Product> _repoProduct)
        {
            repoProduct = _repoProduct;
        }
        public IActionResult Index()
        {

            return View();
        }

        [Route("/urun/{name}-{id}")]
        public IActionResult Detail(string name, int id)
        {
            Product product = repoProduct.GetAll().Include(i => i.ProductPictures).FirstOrDefault(x => x.ID == id) ?? null;
            if (product != null)
            {
                ProductVM productVM = new ProductVM
                {
                    Product = product,
                    SimilarProducts = repoProduct.GetAll().Include(i => i.ProductPictures).Where(w => w.BrandID == product.BrandID && w.ID != product.ID).Take(5)
                };
                return View(productVM);
            }
            else return Redirect("/");
        }
    }
}

InfCommerce.WebUI/ViewComponents/FooterViewComponent.cs
using InfCommerce.BL.Repositories;
using InfCommerce.DAL.DbContexts;
using InfCommerce.DAL.Entities;
using InfCommerce.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace InfCommerce.WebUI.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        SqlRepo<Brand> repoBrand;
        SqlRepo<News> repoNews;
        public FooterViewComponent(SqlRepo<Brand> _repoBrand, SqlRepo<News> _repoNews)
        {
            repoBrand = _repoBrand;
            repoNews = _repoNews;
        }
        public IViewComponentResult Invoke()
        {
            FooterVM footerVM = new FooterVM
            {
                Brands = repoBrand.GetAll(),
                Newses = repoNews.GetAll().OrderByDescending(o => o.RecDate).Take(2)
            };
            return View(footerVM);
        }
    }
}

InfCommerce.WebUI/ViewComponents/HeaderViewComponent.cs
using InfCommerce.BL.Repositories;
using InfCommerce.DAL.Entities;
using Microsoft.AspNetCore.Mvc;

namespace InfCommerce.WebUI.ViewComponents
{
    public class HeaderViewComponent: ViewComponent
    {
        SqlRepo<Category> repoCategory;
        public HeaderViewComponent(SqlRepo<Category> _repoCategory)
        {
            repoCategory = _repoCategory;
        }
        public IViewComponentResult Invoke()
        {
            return View(repoCategory.GetAll());
        }
    }
}

InfCommerce.WebUI/Areas/admin/Views/Home/Login.cshtml
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>InfCommerce</title>
    <link href="/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/vendors/nprogress/nprogress.css" rel="stylesheet">
    <link href="/vendors/animate.css/animate.min.css" rel="stylesheet">
    <link href="/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
              <form method="post" asp-controller="Home" asp-action="Index">
                  <h1>InfCommerce</h1>
                  <div>
                      <input type="text" class="form-control" placeholder="Kullanıcı Adı" required="" />
                  </div>
                  <div>
                      <input type="password" class="form-control" placeholder="Şifre" required="" />
                  </div>
                  <div>
                      <button class="btn btn-primary submit" type="submit">      Giriş     </button>
                      <a class="btn btn-success reset_pass" href="#">Şifreni mi unuttun? </a>
                  </div>

                  <div class="clearfix"></div>
                  <br />
                  <div class="separator">
                      <a class="btn btn-info submit" href="/">Mağazaya Geri Dön</a>
                      <div class="clearfix"></div>
                      <br />
                  </div>
              </form>
          </section>
        </div>
      </div>
    </div>
  </body>
</html>

InfCommerce.WebUI/Areas/admin/Views/Slider/Index.cshtml
@model IEnumerable<Slider>
@{ ViewData["Title"] = "Slider"; }
<div class="x_content col-9 right_col">
    <div class="table-responsive bg-white">
        <table class="table table-striped jambo_table bulk_action">
            <thead>
                <tr class="headings">
                    <th class="column-title">ID </th>
                    <th class="column-title">Başlık </th>
                    <th class="column-title">Açıklama </th>
                    <th class="column-title">Görüntülenme Sırası </th>
                    <th class="column-title">Fiyatı </th>
                    <th class="column-title">Linki </th>
                </tr>
            </thead>

            <tbody>
                @foreach (Slider s in @Model)
                {
    <tr>
        <td class=" ">@s.ID</td>
        <td class=" ">@s.Title</td>
        <td class=" ">@s.Description</td>
        <td class=" ">@s.DisplayIndex</td>
        <td class="a-right a-right ">@s.Price</td>
        <td class=" last">
            <a href="@s.Link">View</a>
        </td>
    </tr>}

            </tbody>
        </table>
    </div>
</div>

InfCommerce.WebUI/Views/Home/Card.cshtml
<!-- Page info -->
<div class="page-top-info">
    <div class="container">
        <h4>Your cart</h4>
        <div class="site-pagination">
            <a href="">Home</a> /
            <a href="">Your cart</a>
        </div>
    </div>
</div>
<!-- Page info end -->
<!-- cart section end -->
<section class="cart-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="cart-table">
                    <h3>Your Cart</h3>
                    <div class="cart-table-warp">
                        <table>
                            <thead>
                                <tr>
                                    <th class="product-th">Product</th>
                                    <th class="quy-th">Quantity</th>
                                    <th class="size-th">SizeSize</th>
                                    <th class="total-th">Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="product-col">
                                        <img src="img/cart/1.jpg" alt="">
                                        <div class="pc-title">
                                            <h4>Animal Print Dress</h4>
                                            <p>$45.90</p>
                                        </div>
                                    </td>
                                    <td class="quy-col">
                                        <div class="quantity">
                                            <div class="pro-qty">
                                                <input type="text" value="1">
                                            </div>
                                        </div>
                                    </td>
                                    <td class="size-col"><h4>Size M</h4></td>
                                    <td class="total-col"><h4>$45.90</h4></td>
                                </tr>
                                <tr>
                                    <td class="product-col">
                                        <img src="img/cart/2.jpg" alt="">
                                        <div class="pc-title">
                                            <h4>Ruffle Pink Top</h4>
                                            <p>$45.90</p>
                                        </div>
                                    </td>
                                    <td class="quy-col">
                                        <div class="quantity">
                                            <div class="pro-qty">
                                                <input type="text" value="1">
                                            </div>
                                        </div>
                                    </td>
                                    <td class="size-col"><h4>Size M</h4></td>
                                    <td class="total-col"><h4>$45.90</h4></td>
                                </tr>
                                <tr>
                                    <td class="product-col">
                                        <img src="img/cart/3.jpg" alt="">
                                        <div class="pc-title">
                                            <h4>Skinny Jeans</h4>
                                            <p>$45.90</p>
                                        </div>
                                    </td>
                                    <td class="quy-col">
                                        <div class="quantity">
                                            <div class="pro-qty">
                                                <input type="text" value="1">
                                            </div>
                                        </div>
                                    </td>
                                    <td class="size-col"><h4>Size M</h4></td>
                                    <td class="total-col"><h4>$45.90</h4></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="total-cost">
                        <h6>Total <span>$99.90</span></h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 card-right">
                <form class="promo-code-form">
                    <input type="text" placeholder="Enter promo code">
                    <button>Submit</button>
                </form>
                <a href="" class="site-btn">Proceed to checkout</a>
                <a href="" class="site-btn sb-dark">Continue shopping</a>
            </div>
        </div>
    </div>
</section>
<!-- cart section end -->
<!-- Related product section -->
<section class="related-product-section">
    <div class="container">
        <div class="section-title text-uppercase">
            <h2>Continue Shopping</h2>
        </div>
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="product-item">
                    <div class="pi-pic">
                        <div class="tag-new">New</div>
                        <img src="/img/product/2.jpg" alt="">
                        <div class="pi-links">
                            <a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
                            <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                        </div>
                    </div>
                    <div class="pi-text">
                        <h6>$35,00</h6>
                        <p>Black and White Stripes Dress</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="product-item">
                    <div class="pi-pic">
                        <img src="./img/product/5.jpg" alt="">
                        <div class="pi-links">
                            <a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
                            <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                        </div>
                    </div>
                    <div class="pi-text">
                        <h6>$35,00</h6>
                        <p>Flamboyant Pink Top </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="product-item">
                    <div class="pi-pic">
                        <img src="./img/product/9.jpg" alt="">
                        <div class="pi-links">
                            <a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
                            <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                        </div>
                    </div>
                    <div class="pi-text">
                        <h6>$35,00</h6>
                        <p>Flamboyant Pink Top </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="product-item">
                    <div class="pi-pic">
                        <img src="./img/product/1.jpg" alt="">
                        <div class="pi-links">
                            <a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
                            <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                        </div>
                    </div>
                    <div class="pi-text">
                        <h6>$35,00</h6>
                        <p>Flamboyant Pink Top </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Related product section end -->

InfCommerce.WebUI/Views/Home/Checkout.cshtml
    <!-- Page info -->
    <div class="page-top-info">
        <div class="container">
            <h4>Your cart</h4>
            <div class="site-pagination">
                <a href="">Home</a> /
                <a href="">Your cart</a>
            </div>
        </div>
    </div>
    <!-- Page info end -->
    <!-- checkout section  -->
    <section class="checkout-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 order-2 order-lg-1">
                    <form class="checkout-form">
                        <div class="cf-title">Billing Address</div>
                        <div class="row">
                            <div class="col-md-7">
                                <p>*Billing Information</p>
                            </div>
                            <div class="col-md-5">
                                <div class="cf-radio-btns address-rb">
                                    <div class="cfr-item">
                                        <input type="radio" name="pm" id="one">
                                        <label for="one">Use my regular address</label>
                                    </div>
                                    <div class="cfr-item">
                                        <input type="radio" name="pm" id="two">
                                        <label for="two">Use a different address</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row address-inputs">
                            <div class="col-md-12">
                                <input type="text" placeholder="Address">
                                <input type="text" placeholder="Address line 2">
                                <input type="text" placeholder="Country">
                            </div>
                            <div class="col-md-6">
                                <input type="text" placeholder="Zip code">
                            </div>
                            <div class="col-md-6">
                                <input type="text" placeholder="Phone no.">
                            </div>
                        </div>
                        <div class="cf-title">Delievery Info</div>
                        <div class="row shipping-btns">
                            <div class="col-6">
                                <h4>Standard</h4>
                            </div>
                            <div class="col-6">
                                <div class="cf-radio-btns">
                                    <div class="cfr-item">
                                        <input type="radio" name="shipping" id="ship-1">
                                        <label for="ship-1">Free</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <h4>Next day delievery  </h4>
                            </div>
                            <div class="col-6">
                                <div class="cf-radio-btns">
                                    <div class="cfr-item">
                                        <input type="radio" name="shipping" id="ship-2">
                                        <label for="ship-2">$3.45</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="cf-title">Payment</div>
                        <ul class="payment-list">
                            <li>Paypal<a href="#"><img src="img/paypal.png" alt=""></a></li>
                            <li>Credit / Debit card<a href="#"><img src="img/mastercart.png" alt=""></a></li>
                            <li>Pay when you get the package</li>
                        </ul>
                        <button class="site-btn submit-order-btn">Place Order</button>
                    </form>
                </div>
                <div class="col-lg-4 order-1 order-lg-2">
                    <div class="checkout-cart">
                        <h3>Your Cart</h3>
                        <ul class="product-list">
                            <li>
                                <div class="pl-thumb"><img src="img/cart/1.jpg" alt=""></div>
                                <h6>Animal Print Dress</h6>
                                <p>$45.90</p>
                            </li>
                            <li>
                                <div class="pl-thumb"><img src="img/cart/2.jpg" alt=""></div>
                                <h6>Animal Print Dress</h6>
                                <p>$45.90</p>
                            </li>
                        </ul>
                        <ul class="price-list">
                            <li>Total<span>$99.90</span></li>
                            <li>Shipping<span>free</span></li>
                            <li class="total">Total<span>$99.90</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- checkout section end -->
    

InfCommerce.WebUI/Views/Home/Contact.cshtml
    <!-- Page info -->
    <div class="page-top-info">
        <div class="container">
            <h4>Contact</h4>
            <div class="site-pagination">
                <a href="">Home</a> /
                <a href="">Contact</a>
            </div>
        </div>
    </div>
    <!-- Page info end -->
    <!-- Contact section -->
    <section class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 contact-info">
                    <h3>Get in touch</h3>
                    <p>Main Str, no 23, New York</p>
                    <p>+546 990221 123</p>
                    <p>hosting@contact.com</p>
                    <div class="contact-social">
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                    <form class="contact-form">
                        <input type="text" placeholder="Your name">
                        <input type="text" placeholder="Your e-mail">
                        <input type="text" placeholder="Subject">
                        <textarea placeholder="Message"></textarea>
                        <button class="site-btn">SEND NOW</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="map"><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d14376.077865872314!2d-73.879277264103!3d40.757667781624285!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1546528920522" style="border:0" allowfullscreen></iframe></div>
    </section>
    <!-- Contact section end -->
    <!-- Related product section -->
    <section class="related-product-section spad">
        <div class="container">
            <div class="section-title">
                <h2>Your Favorites</h2>
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="product-item">
                        <div class="pi-pic">
                            <div class="tag-new">New</div>
                            <img src="./img/product/2.jpg" alt="">
                            <div class="pi-links">
                                <a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
                                <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                            </div>
                        </div>
                        <div class="pi-text">
                            <h6>$35,00</h6>
                            <p>Black and White Stripes Dress</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="product-item">
                        <div class="pi-pic">
                            <img src="./img/product/5.jpg" alt="">
                            <div class="pi-links">
                                <a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
                                <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                            </div>
                        </div>
                        <div class="pi-text">
                            <h6>$35,00</h6>
                            <p>Flamboyant Pink Top </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="product-item">
                        <div class="pi-pic">
                            <img src="./img/product/9.jpg" alt="">
                            <div class="pi-links">
                                <a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
                                <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                            </div>
                        </div>
                        <div class="pi-text">
                            <h6>$35,00</h6>
                            <p>Flamboyant Pink Top </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="product-item">
                        <div class="pi-pic">
                            <img src="./img/product/1.jpg" alt="">
                            <div class="pi-links">
                                <a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
                                <a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
                            </div>
                        </div>
                        <div class="pi-text">
                            <h6>$35,00</h6>
                            <p>Flamboyant Pink Top </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Related product section end -->
   

InfCommerce.WebUI/Views/Home/Iletisim.cshtml
@{
    //Layout = null;
    Layout = "~/Views/Shared/XLay.cshtml";
}

<h1>Iletisim</h1>
Formu Dolduran Kişi: @TempData["kisi"]

InfCommerce.WebUI/Views/Shared/Components/Header/Default.cshtml
@model IEnumerable<Category>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>	
<!-- Header section -->
	<header class="header-section">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 text-center text-lg-left">
						<!-- logo -->
						<a href="./index.html" class="site-logo">
							<img src="img/logo.png" alt="">
						</a>
					</div>
					<div class="col-xl-6 col-lg-5">
						<form class="header-search-form">
							<input type="text" placeholder="Search on divisima ....">
							<button><i class="flaticon-search"></i></button>
						</form>
					</div>
					<div class="col-xl-4 col-lg-5">
						<div class="user-panel">
							<div class="up-item">
								<i class="flaticon-profile"></i>
								<a href="#">Sign</a> In or <a href="#">Create Account</a>
							</div>
							<div class="up-item">
								<div class="shopping-card">
									<i class="flaticon-bag"></i>
									<span>0</span>
								</div>
								<a href="#">Shopping Cart</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<nav class="main-navbar">
			<div class="container">
				<!-- menu -->
				<ul class="main-menu">
					<li><a href="#">Ana Sayfa</a></li>
				   @foreach (Category c in Model)
				   {
					   <li><a href="#">@c.Name</a></li>
				   }				
				</ul>
			</div>
		</nav>
	</header>
	<!-- Header section end -->

InfCommerce.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
	<head>
		<title>Divisima | eCommerce Template</title>
		<meta charset="UTF-8">
		<meta name="description" content=" Divisima | eCommerce Template">
		<meta name="keywords" content="divisima, eCommerce, creative, html">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="img/favicon.ico" rel="shortcut icon"/>
		<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">
		<link rel="stylesheet" href="/css/main.min.css"/>
	</head>
	<body>
		@await Component.InvokeAsync("Header")
		@RenderBody()
		@await Component.InvokeAsync("Footer")
		<script src="/js/main.min.js"></script>
	</body>
</html>

InfCommerce.WebUI/Views/Shared/_ProductItem.cshtml
@model Product
<div class="product-item">
    <div class="pi-pic">
        @if (Model.ProductPictures.Any())
        {
<img src="@Model.ProductPictures.FirstOrDefault().Path" alt="@Model.Name"> }
            else
            {
<img src="/img/product/noproduct.jpg" alt="@Model.Name">}
        <div class="pi-links">
            <a asp-controller="Product" asp-action="Detail" asp-route-name="@GeneralTool.ConvertURL(Model.Name)" asp-route-id="@Model.ID" class="add-card"><i class="flaticon-bag"></i><span>SEPETE EKLE</span></a>
        </div>
    </div>
    <div class="pi-text">
        <h6 style="text-decoration:line-through;color:red">@Model.DiscountPrice TL</h6>
        <h6>@Model.Price TL</h6><br>
        <h5>@Model.Name</h5>
    </div>
</div>